spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route
          uri: https://ww.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://ww.qq.com
          predicates:
            - Query=url,qq
  application:
    name: shopping-gateway
server:
  port: 88
